#!/bin/sh


# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
for i in /etc/init.d/S??* ;do
     case "$i" in
	*)
		if [ "$i" = "/etc/init.d/S01demo" ]; then
            "$i" start
            sleep 2 
	    else
            # Start other scripts as usual
            "$i" start
        fi
	    ;;
    esac
done

